services:
  postgres:
    image: postgres:15
    container_name: pm-it-postgres
    environment:
      POSTGRES_USER: pm_user
      POSTGRES_PASSWORD: pm_password
      POSTGRES_DB: pm_db
    ports:
      - "5432:5432"
    volumes:
      - pm-it-postgres-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: pm-it-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_IMPORT: /opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--import-realm"]
    ports:
      - "8081:8080"
    volumes:
      - ./src/test/resources/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

volumes:
  pm-it-postgres-data:
