spring:
  application.name: password-manager-v2

  datasource:
    url: jdbc:postgresql://localhost:5432/pm-db
    username: pm-psql-db-user
    password: supa-secure

  jpa:
    hibernate.ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

app:
  encryption.key: zlOUCikArtsQvFCE/8lsDw4tY88ozFGJoczfNGZxd7k=
  jwt:
    secret: 5w4hskzzzwQGuxHgcfHMSxs5kDXjhPtpBOu+z+aZdHugoBO6fjBHRbNjQ+elw+6RZihrIGgKMYd4qb3SoAp2JA==
    expiration-ms: 3600000
